version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock_visualizer_image_flask
    container_name: flask_stock_visualizer
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"
